move logout event to service
OpenStackweb/openstackid pull request #33
Opened 2023-08-30 15:33 UTC by romanetar

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3365689&stafilter=NotComplete&fileview=grid

Signed-off-by: romanetar <roman_ag@hotmail.com>

2023-08-30 19:31 UTC, smarcet requested changes
@romanetar please review comments

2023-08-31 08:14 UTC, romanetar commented on app/libs/Auth/AuthService.php
>          Log::debug("AuthService::logout");
done

2023-08-31 08:16 UTC, romanetar commented
@smarcet review comments addressed

2023-11-07 19:36 UTC, smarcet approved these changes
LGTM

2023-11-07 19:36 UTC, merged